### PR TITLE
Chatroom UI

### PR DESCRIPTION
**Pull request by memelamb**
i found that my vs code needs to update the expo to run it. there is modification in package.json, tsconfig.json. chatroom UI done. tell me if any changes needed :)

### CODE REVIEW

**Review by zyronhosuiting — COMMENTED** [review]
Understand the difference between a scrollview and flatlist : https://pankajhasmukh2014.medium.com/difference-between-scrollview-and-flatlist-react-native-20a2e49238f9

Advanced: https://shopify.engineering/instant-performance-upgrade-flatlist-flashlist

Don't use HTML and elements, React Native uses its own set of components for forms like TextInput and TouchableOpacity. Switch to those to avoid errors: https://reactnative.dev/

Some typescript issue: try vsCode plugin like eslint

**Comment by memelamb** [comment]
changed. please tell me if any change is needed :))

**Comment by zyronhosuiting** [comment]
Great work for your first time using React Native!

 A few things to be aware for future work:

- Pull the Latest Changes from the Main Branch Daily: It's important to regularly pull updates from the main branch, ideally at the start of your workday. This ensures your local development environment is always up-to-date with the latest code and reduces the risk of merge conflicts later on. Consistently staying in sync with the main branch helps keep the team aligned and avoids surprises when merging your changes.

- Format Your Code Consistently: Always format your code according to the project's coding standards before committing any changes. Many teams use tools like Prettier or ESLint to automatically format the code. Ensuring that your code is properly formatted improves readability, makes it easier to review, and maintains consistency across the entire codebase.

- Leave Blank Lines for Readability: Incorporating blank lines where appropriate, such as between logical blocks of code, enhances readability. This small habit can make your code more understandable for others and for yourself when revisiting it later.

**Comment by zyronhosuiting** [comment]
A few suggestions for improving the chatroom feature:

- Implement SafeAreaView: To ensure the UI is properly rendered within the safe area boundaries, use SafeAreaView from the react-native-safe-area-context library. You can find more details here: [Safe Area Documentation](https://reactnavigation.org/docs/handling-safe-area/).

- Refactor the Dialogue into a Reusable Component: Consider extracting the chat dialogue into a separate component. This component should accept an owner prop, which will determine whether the dialogue is aligned to the left or right, based on the message sender.

- Consider adding icon, timestamps or "read" receipts for each message. This can improve the chatroom’s functionality and enhance the user experience.

- You can optimize the buttonHandler and renderItem functions using useCallback to prevent unnecessary re-renders.

**Pull request merged**
